### ISSUE TITLE
CODE CLEANUP PROJECT

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/SwiftBrowser#3]
CLEAN UP CODE OF BROWSER.

browser code is very bad. I have random comments, no usefull comments, weird variable names and bad implementations. this happen because I first started the project before I had good coding practices. In addition to this I had to make browser by june which got delayed and I had to rush it leaving no time for code improvement.

Here are changes to be made, I ordered if from easiest to significantly hard:
**NOTE I HAVENT COMPLETED THIS LIST**

- [ ] remove all comments. except the one in permissions page.

- [ ] re name and re organize files to correct folders
- [ ] **Add comments explaining which code does what. do this earlier so when I come back to project I wont be like what does this do**

- [ ] change names of objects to something better, shorter and more accurate to what it does

- [ ] Move classes to models folder

- [ ] re implement how navigation works - possibly use service

- [ ] re implement how history works

- [ ] switch some void functions to task because task is better for those scenarios 

- [ ] any functions which take up more than one screen should be changed

- [ ] re do how permissions work
- [ ] try to have zero warning and maybe also zero vs messages
- [ ] remove redundant await / async
- [ ] handle exceptions
- [ ] remove unused stuff

~~- [ ] create unit tests even if I dont know what it means~~ canceled i dont need unit tests after learning what it was it. going to add unit tests to the webview 2 chromium browser instead

- [ ] replace try{}catch{try{}catch{}}} code
- [ ] replace if else if else if else if else if else code
- [ ] remove and replace redundant code - this code is exist because the app was different when it first started.
- [ ] in app notification service
- [ ] format code maybe use a extension for it

- [ ] add readme to GitHub
- [ ] add docs for adding extensions
- [ ] reimplement how extensions work and add api

**Comment by Jaiganeshkumaran** [comment]
For formatting code, you can use the built-in option which you can find under Edit->Advanced. For XAML files, I recommend using XAML Styler.

**Comment by FireCubeStudios** [comment]
thanks i didnt know about that i ma also going to use resharper.

**Comment by FireCubeStudios** [comment]
refactored a lot going to close this issue because i cant fix everything. hopefully i do better in the chromium version will add comments and maybe use mvvm and x:bind
