### ISSUE TITLE
Speed up development and add gesture UI and UX also :

### ISSUE THREAD

**Issue by fisforfaheem** [FireCubeStudios/SwiftBrowser#35]
Please focus on windows 10 store, pay microsoft to feature your app in free apps! also make ui and copy opera and edge features now

**Comment by FireCubeStudios** [comment]
I will add support for gestures to swipe back and forth web pages.
I wont pay Microsoft even if its possible-to get my app featured it would need more positive reviews so you can help by leaving an honest review.  
what features from edge and opera do you want me to include ?

**Comment by fisforfaheem** [comment]
Thanks for reply, At this point I want the app to become popular and I want more people using it, Because it is so modern feeling browser.
Of-course you dont wanna pay for things, at least write to windows central to write about your browser or do something similar.
I really hope that you transfer the core to latest chromium 85 version in advance.
Opera has built in VPN,Adblock(honest), and animations.
Please make the experience more intuitive and engaging and use FLUENT UI in even before edge browser itself.
Also please please speed up the updates and also make a website with an .appx file download option.

**Comment by FireCubeStudios** [comment]
Thanks for the feedback.
there will be a separate browser which is powered by chromium. it might also support every chrome extension including adblocker.
updates take time to get certified in the store this can take upto 3 business days plus the time to make features for updates. I also wont make a website for separate downloads except maybe for chromium version.
My browser was part of launch 2020 and featured in windowscentral, neo win, mspu and many more sites. if you want to help make it more popular you can review the app in the store and share it!

**Comment by fisforfaheem** [comment]
Yes I will, It would mean alot to me. Also looking forward for chromium
version, stop work on this version and focus on chromium 85+
Also, I wish i could contribute but i am just a student doing BSIT with
little to no coding skills! Hope to build apps like yours one day.
Again also focus on live tiles, ICON, and notifications i next version

**Comment by FireCubeStudios** [comment]
I have to work on both browsers as chromium doesnt work in xbox, mixed reality or windows phone. good luck in learning programming.

**Comment by fisforfaheem** [comment]
people won't use it on xbox or windows phone, Think about PC and Tablets
for now. and .net 6 or .net 5

**Comment by FireCubeStudios** [comment]
xbox, mobile and mixed reality dont have alternative web browsers so I focus there.

**Comment by fisforfaheem** [comment]
Oh i see, keep updating and using new stuff cool!

**Comment by Sathware** [comment]
Doesn't the new WebView for WinUI 3.0 use Edge(Chromium)? You may not even need to develop/rewrite a separate browser that uses. the chromium engine.

**Comment by FireCubeStudios** [comment]
No I will have separate app

**Comment by fisforfaheem** [comment]
Waiting for that app! also please take some design fro myTube APP
