### ISSUE TITLE
Github doesn't render correctly in SwiftBrowser.

### ISSUE THREAD

**Issue by Sathware** [FireCubeStudios/SwiftBrowser#41]
Hey, I heard about swift browser from the uwp community, and I have to say that I'm very impressed. Though whenever I try to go to github, it doesn't render properly or at all.

**Comment by FireCubeStudios** [comment]
were you using the built in adblocker?

**Comment by Sathware** [comment]
Yeah, I just turned it off, and it worked fine. Sorry, didn't know that was the problem, I'll close this issue now.
