### ISSUE TITLE
Ability to install apps

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [FireCubeStudios/SwiftBrowser#43]
Similar to Microsoft Edge, you should be able to install websites as apps. Currently, click the app button only opens in an app like window but it doesn't actually install it. Installed apps should be available on the Start Menu and you should be able to uninstall it from Apps & Features in the Settings app.

**Comment by FireCubeStudios** [comment]
there is a feature called hosted apps in v2004. once this supports uwp i will add this feature. ms edge also uses hosted apps to install pwa
