### ISSUE TITLE
Consistent pages

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [FireCubeStudios/SwiftBrowser#45]
Currently, pages like history, favorite look completely different which confuses me. Please make it consistent.

**Comment by FireCubeStudios** [comment]
good idea, i will make it consistent as part of my code clenaup.

**Comment by FireCubeStudios** [comment]
ok started work on this issue

**Comment by FireCubeStudios** [comment]
i made both of them identical closing the issue now
