### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [FireCubeStudios/SwiftBrowser#48]
I am working on improving Swift Browser but I can't build it since KeePassLib could not be found on Nuget. If this package belongs to you, please send it to me.

**Comment by Jaiganeshkumaran** [comment]
Sorry, I disabled preview packages and it KeePasLib was in preview. It works now.

**Comment by Jaiganeshkumaran** [comment]
Now I can build the project but I can't install it since you have not provided the certificate. I can generate one for testing but please provide the original.

**Comment by FireCubeStudios** [comment]
ok i will do that once i get to my pc

**Comment by Jaiganeshkumaran** [comment]
Thanks!

**Comment by FireCubeStudios** [comment]
hey @Jaiganeshkumaran im still new to this but where can i find the certificate and how to send it?

**Comment by Jaiganeshkumaran** [comment]
The certificate should be in the project folder. By default it’s ignored by git so you need to edit the hidden gitignore file. Remember that the certificate in your project is just a test certificate. When you upload it to the store, they generate one for you which is recognized by all Windows devices. For the test certificate you need to manually trust it.

**Comment by FireCubeStudios** [comment]
sorry i couldnt find it check discord i asked some quesiton
