### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [FireCubeStudios/SwiftBrowser#54]
In WinUI tabview, the default shortcut for closing the current tab is Ctrl + F4. This shortcut is used many apps like Visual Studio but browsers usually use Ctrl + W instead of Ctrl + F4. I'd suggest you to keep the default shortcut but also add Ctrl + W as another shortcut.

**Comment by FireCubeStudios** [comment]
ok, i also renamed it to add keyboard shortcuts because i dont have many keyboard shortcuts like ctrl + f, ctrl + h etc.

**Comment by FireCubeStudios** [comment]
update added ctrl + w shortcut will add more though

**Comment by FireCubeStudios** [comment]
also added ctrl +f and ctrl + h

**Comment by FireCubeStudios** [comment]
ctrl + r added

**Comment by FireCubeStudios** [comment]
closing the issue as i added several keyboard shortcuts
